[package]
name = "tiez-bin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "modular-clipboard"
path = "src/main.rs"

[dependencies]
tiez-core = { workspace = true }
tiez-app = { workspace = true }
tiez-ui = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
directories = { workspace = true }
